//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by zigbee.rc
//
#define IDC_VIEWLICENSES                2
#define IDM_STATIC                      100
#define IDR_MENU                        101
#define IDM_ERRORS                      101
#define IDM_QUIT                        102
#define IDR_ACCELERATORS                102
#define IDM_LOADEDFFILE                 103
#define IDC_SENSITIVITY                 104
#define IDC_TIMEBASE                    105
#define IDC_LP                          106
#define IDM_FULLSCREEN                  107
#define IDM_SAMPLE_STOP_NORMAL          108
#define IDM_SYSTEMCHECK                 109
#define IDT_BATSTATUS_TIMER             110
#define IDT_REDRAW_TIMER                111
#define IDM_SIGNAL_DISPLAY_MODE         112
#define IDM_TESTCONNSCRIPT              113
#define IDI_ICON                        114
#define IDT_RTC_TIMER                   114
#define IDI_BATLOW1                     116
#define IDD_RECORDINGINFORMATION        119
#define IDI_BATLOW2                     122
#define IDD_PATIENTINFO                 130
#define IDD_SCREENSIZE                  132
#define IDI_EXIT                        141
#define IDI_PARAMETERS                  142
#define IDI_PATIENT                     143
#define IDI_RECORDING                   144
#define IDI_ANNOTATIONS                 145
#define IDI_RECORD                      146
#define IDI_STOP                        147
#define IDI_ALERT                       153
#define IDI_CHECK                       154
#define IDB_TRAFFIC_GRN                 161
#define IDB_TRAFFIC_RED                 162
#define IDB_TRAFFIC_REDYEL              163
#define IDB_TRAFFIC_YEL                 166
#define IDB_TRAFFIC_OFF                 167
#define IDM_SAMPLE_START                202
#define IDM_SAMPLE_STOP                 203
#define IDM_PATIENTINFO                 204
#define IDM_ANNOTATIONS_DISPLAY         999
#define IDC_ADMINISTRATIONCODE          1023
#define IDC_TECHNICIAN                  1024
#define IDC_CHARSREMAINING2             1025
#define IDC_DEVICE                      1026
#define IDC_COMMENTS                    1027
#define IDC_CHARSREMAINING1             1028
#define IDC_ADDITIONALCOMMENTS          1029
#define IDC_CHARSREMAINING              1029
#define IDC_DISKSPACE                   1030
#define IDC_CHARSREMAINING3             1030
#define IDC_SCREENWIDTH                 1033
#define IDC_SCREENHEIGHT                1034
#define IDC_SCREENWIDTHSPIN             1035
#define IDC_SCREENHEIGHTSPIN            1036
#define IDC_VERTICALRULER               1038
#define IDC_HORIZONTALRULER             1039
#define IDC_HOSTNAME                    1042
#define IDC_SSHHOSTNAME                 1042
#define IDC_USERNAME                    1043
#define IDC_CONNSCRIPT_FILE             1043
#define IDC_PASSWORD                    1044
#define IDC_SSHPORT                     1044
#define IDC_REMOTEPATH                  1045
#define IDC_SSHREMOTEPATH               1045
#define IDC_SSHCONNTIMEOUT              1046
#define IDC_SSHLOWSPEEDLIMIT            1047
#define IDC_AUTOMATICUPLOAD             1048
#define IDC_DIALCONNSCRIPT              1049
#define IDC_SSHLOWSPEEDTIME             1050
#define IDC_ICC_DIALCONN                1050
#define IDC_RICHEDIT21                  1051
#define IDC_EXTLIBRARIES                1051
#define IDC_SYSLINK1                    1052
#define IDC_SYSLINK2                    1053
#define IDC_SSHUSERPWD                  1053
#define IDC_SSHSERVERCONFIG             1054
#define IDC_FSAMPLE                     1056
#define IDC_ELECTRODES                  1057
#define IDC_STREAMINGSERVERIPv4         1058
#define IDC_STREAMINGSERVERPORT         1059
#define IDC_MAXNSENDMSGFAILURES         1060
#define IDC_MAXNWAIT4REPLYFAILURES      1061
#define IDC_STREAMINGUSERPWD            1062
#define IDC_STREAMINGENABLED            1063
#define IDC_ICC_EXECCONNSCRIPT          1064
#define IDC_CONNECTIONSLISTBOX          1065
#define IDC_ICC_CONNECTIONSLISTBOX      1065
#define IDC_ICC_CONNSCRIPT_FILE         1066
#define IDD_ANNOTATIONS                 3010
#define IDD_SETTINGS                    3020
#define IDD_SSHCONFIG                   3021
#define IDD_ABOUTBOX                    3022
#define IDD_STREAMINGCONFIG             3023
#define IDD_INTERNETCONFIG              3024
#define IDA_CTRLS                       10202
#define IDA_CTRLE                       10203
#define IDC_NAME                        20401
#define IDC_PIC                         20402
#define IDC_BDATEDAY                    20403
#define IDC_BDATEMONTH                  20404
#define IDC_BDATEYEAR                   20405
#define IDC_SEXM                        20406
#define IDC_SEXF                        20407
#define IDC_SEXU                        20408
#define IDC_AN1                         30101
#define IDC_AN2                         30102
#define IDC_AN3                         30103
#define IDC_AN4                         30104
#define IDC_AN5                         30105
#define IDC_AN6                         30106
#define IDC_AN7                         30107
#define IDI_BATFULL                     30201
#define IDC_CH0                         30202
#define IDC_CH1                         30203
#define IDC_CH2                         30204
#define IDC_CH3                         30205
#define IDC_CH4                         30206
#define IDC_CH5                         30207
#define IDC_FNAME                       30208
#define IDC_FNAME_BUTTON                30209
#define IDC_TXPOWER                     30211
#define IDC_BATTYPE                     30211
#define IDC_SERPORT                     30212
#define IDM_RECORDINGINFORMATION        40015
#define IDA_CTRLR                       40016
#define IDA_CTRLP                       40018
#define IDM_PARAMETERS                  40023
#define IDM_UTILITIES_EDFFILEEDITOR     40025
#define ID_ABOUT                        40026
#define IDM_ABOUT                       40027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
